import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#fff' },
  container: { padding: 16 },
  containerCentered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  logoImage: { width: 150, height: 150, marginBottom: 20 },
  card: {
    width: '100%',
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 12,
    elevation: 2,
    alignItems: 'center',
  },
  input: {
    borderWidth: 1,
    borderColor: '#ddd',
    padding: 12,
    borderRadius: 8,
    marginBottom: 10,
    width: '100%',
  },
  button: {
    backgroundColor: '#2b6cb0',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  buttonText: { color: '#fff', fontWeight: '600' },
  link: { color: '#2b6cb0', marginTop: 15 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderColor: '#eee',
  },
  headerTitle: { fontSize: 18, fontWeight: '600' },
  sectionTitle: { fontSize: 20, fontWeight: '700', marginBottom: 12 },
  bookCard: { flex: 0.48, marginVertical: 8 },
  bookCover: {
    width: '100%',
    height: width * 0.6,
    borderRadius: 8,
    marginBottom: 8,
  },
  bookTitleSmall: { fontWeight: '600', fontSize: 14 },
  bookDetailTop: { flexDirection: 'row' },
  bookDetailCover: {
    width: width * 0.35,
    height: width * 0.55,
    borderRadius: 8,
  },
  bookDetailInfo: { flex: 1, marginLeft: 16 },
  bookTitle: { fontSize: 22, fontWeight: '800' },
  bookAuthor: { fontSize: 16, color: '#666', marginTop: 4 },
  availabilityText: { fontSize: 14, fontWeight: 'bold', marginTop: 8 },
  descriptionContainer: { marginTop: 24 },
  descriptionText: { fontSize: 16, lineHeight: 24 },
  readMoreText: {
    color: '#2b6cb0',
    fontWeight: 'bold',
    marginTop: 5,
  },
  cartItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  cartItemImage: { width: 40, height: 60, borderRadius: 4, marginRight: 12 },
  cartItemTitle: { flex: 1, fontSize: 16 },
  checkoutBox: {
    padding: 16,
    borderTopWidth: 1,
    borderColor: '#eee',
    backgroundColor: '#fafafa',
  },
  checkoutText: { fontSize: 16, marginBottom: 10, textAlign: 'center' },
});
